[data] #7 Create room database with repository
mindgarden-app/mindgarden-android pull request #10
Opened 2021-06-09 17:45 UTC by EuneeChung

레파지토리를 적용한 Room Database 추가했습니다.
- Dao : GardenDao, DiaryDao, UserDao
- Entity: Garden, Diary, User
- [Repository 참고 래퍼런스](https://github.com/android/architecture-samples/tree/dev-todo-mvvm-live/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/data)  

예시로 NickName Activity 에 view model 과 repository 연결해놨습니다.  

Injection을 처음 해봐서 검토 부탁드려요 ;)
view model, repository 연결 부분에 대한 더 좋을 것 같은 방안 있으면 리뷰해주세요! 
그 이외에도 언제나 환영입니다 !

2021-06-10 00:17 UTC, joyObigo requested changes
고생 많았어요~! @EuneeChung  멋져요!!
제 리뷰 보시고 수정 한번 고려해 봐주세요

2021-06-10 00:17 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/Injection.kt
> +    private fun createMindGardenRepository(context: Context): MindGardenRepository {
개인적인 의견인데, Injection 파일이니까 provide 함수만 있으면 더 기능이 명확해 보일 것 같아요
그래서 **createMinGardenRepository()**를 **createMindGardenLocalDataSource()**랑 합치고
createMindGardenDataSource()를 provideMindGardenDataSource로 이름을 바꾸는 건 어떨까요?

2021-06-10 00:17 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    val date:String,
date는 아래 Android Developer 참고해서 Date 타입으로 저장하면 어떨까요?
String으로 저장하기보다 Date로 저장하고 convert 쓰는게 여러 곳에서 활용하기 좋을 것 같아서요!
https://developer.android.com/training/data-storage/room/referencing-data?hl=ko

2021-06-10 00:17 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    val weather:Int,
weather text도 추가해야 할 것 같습니다!

2021-06-10 00:17 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Garden.kt
> +    @ColumnInfo(name="date")
여기도 Diary Entity랑 마찬가지로 Date로 저장하면 어떨까요

2021-06-10 00:25 UTC, godjoy requested changes
고생 많으셨습니다!!

2021-06-10 00:25 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/Injection.kt
> +    private fun createMindGardenRepository(context: Context): MindGardenRepository {
개인적인 의견인데, Injection 파일이니까 provide 함수만 있으면 더 기능이 명확해 보일 것 같아요
그래서 **createMinGardenRepository()**를 **createMindGardenLocalDataSource()**랑 합치고
createMindGardenDataSource()를 provideMindGardenDataSource로 이름을 바꾸는 건 어떨까요?

2021-06-10 00:25 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    @ColumnInfo(name="date")
date는 아래 Android Developer 참고해서 Date 타입으로 저장하면 어떨까요?
String으로 저장하기보다 Date로 저장하고 convert 쓰는게 여러 곳에서 활용하기 좋을 것 같아서요!
https://developer.android.com/training/data-storage/room/referencing-data?hl=ko

2021-06-10 00:25 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    @ColumnInfo(name="weather")
weather text도 추가해야 할 것 같습니다!

2021-06-10 00:25 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Garden.kt
> +    val data:Long,
여기도 Diary Entity랑 마찬가지로 Date로 저장하면 어떨까요

2021-06-10 02:01 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    @ColumnInfo(name="weather")
오 그렇게요! 놓치고 있었는데 감사합니다 😊

2021-06-10 02:02 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Diary.kt
> +    @ColumnInfo(name="date")
오 convert해서 저장하면 되겠다고 생각했는데 생각해보니 변환해서 저장할 필요가 없네요
수정하겠습니다!

2021-06-10 02:02 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/model/Garden.kt
> +    val data:Long,
네! 좋아요

2021-06-10 02:12 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/Injection.kt
> +    private fun createMindGardenRepository(context: Context): MindGardenRepository {
마지막에 함수의 이름을 바꾸라고 하셨는데 createMindGardenDataSource() 이거 말씀하신거가 createMinGardenRepository()이거를 뜻하는게 맞을까요?

provide 랑 create 는 동기화와 생성으로 행동이 다르다고 해서 분리 해놨던건데 Injection 개념에 대한 이해가 조금 부족했던거 같아요! 래퍼런스 더 찾아보고 고민해보겠습니다!

의견 감사합니다 🥰

2021-06-12 12:56 UTC, Cho2018 requested changes
너무나도 고생 많으셨습니다!! 👍👍 
덕분에 Room 공부하는데 많은 도움이 됩니다!
감사합니다!! :)
(수정한다고 하셔서 Request changes 했습니다~)

2021-06-12 12:56 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/model/User.kt
> +    val password:String
password가 어떤 것을 의미하는지 궁금합니다.
nickname 만으로도 충부하지 않을까 싶어서요.

2021-06-12 12:56 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/DiaryDao.kt
> +    fun editDiary(diary: Diary):Int
editDiary 대신에 updateDiary 여야 하지 않나요?? 궁금합니다!

2021-06-12 12:56 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/GardenDao.kt
> +}
changeTree는 어떤 의미인지 궁금합니다!!

2021-06-12 12:56 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/UserDao.kt
> +    fun deleteUser(user: User):Int
changePassword와 deleteUser는
interface MindGardenDataSource 에 들어가지 않아도 괜찮은지 궁금합니다!

2021-06-13 05:48 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/model/User.kt
> +    val password:String
암호 !! 페이지가 있어서 암호 저장하려고 만들었어요 ! 
생각해보니 Nullable 로 만들어야겠군요

2021-06-13 05:51 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/DiaryDao.kt
> +    fun editDiary(diary: Diary):Int
업데이트보다 다이어리를 수정하는 행동이라서 이름 지을떄 사람의 행동에 대해서 초점을 두고 Edit 가 더 자연스러운것 같아서 edit 로 정했어요!

2021-06-13 05:55 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/GardenDao.kt
> +}
음 혹시나 나무 자리를 변경하는 기능이 추가될까 해서 만들었습니다! 룸이랑 레파지토리 기반을 만들 때, update에 관련해서 만들다가 이런 기능도 있으면 좋지 않을까 해서 만들었는데 말하는걸 까먹었어요!! 짚어주셔서 감사합니다 . 나무 옮기는 기능에 대해서 회의떄 말해봅시다  -!

2021-06-13 05:59 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/UserDao.kt
> +    fun deleteUser(user: User):Int
레파지토리를 구현한 이유가 local과 remote를 관계없이 동일한 인터페이스로 데이터를 관리할 수 있도록이라고 생각합니다. 고로 데이터를 관리하는 인터페이스는 레파지토리에 속해야 된다고 생각합니다

혹시 어떤 이유에서 들어가지 않아도 되는지 여쭤보시는건지 물어봐도 될까요?

2021-06-13 08:18 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/source/local/UserDao.kt
> +    fun deleteUser(user: User):Int
아 제 말이 모호했네요.. 들어가야 한다는 의미였습니다!! 
레파지토리를 보면 changePassword와 deleteUser가 없어 질문했습니다

상세하게 설명해주셔서 감사합니다 🙏

2021-06-13 09:04 UTC, merged