[feature]#9 diaryList setting
mindgarden-app/mindgarden-android pull request #11
Opened 2021-06-10 12:47 UTC by Cho2018

diaryList 기초 작업을 진행했습니다.

정상 작동 구현을 확인하기 위해 임의로 DB 작업 등을 진행하였습니다.
나중에 여러분들의 DB 작업을 이용하여 수정하겠습니다.
(이 때, 패키지 변경, 컨벤션 규칙 적용, 디자인 등 여러가지 수정할게요... )

- recyclerView를 이용한 목록 구현
- AddActivity를 통해 일기 추가
- 목록 LongClick 시, 일기 삭제

여러 글들을 참고하고 공부하며 하고 있는데 부족한 게 많네요..
보고 이건 아니다 하는 부분들 혹은 더 좋은 방향이 있으면 다 말해주세요!!!!!!!
참고해서 수정하도록 하겠습니다!!

2021-06-10 12:51 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val adapter = DiaryListRecyclerViewAdapter({ diary ->
목록 LongClick 시, 일기가 삭제됩니다.
지금은 삭제 정상 작동을 확인하기 위해 임의로 Dialog로 구현했습니다.

2021-06-10 12:52 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +            deleteDialog(diary)
목록 LongClick 시, 일기가 삭제됩니다.
지금은 삭제 정상 작동을 확인하기 위해 임의로 Dialog로 구현했습니다.

2021-06-10 12:52 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        })
목록 LongClick 시, 일기가 삭제됩니다.
지금은 삭제 정상 작동을 확인하기 위해 임의로 Dialog로 구현했습니다.

2021-06-10 12:57 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        //diaryListViewModel = ViewModelProvider(this).get(DiaryListViewModel::class.java)
이 부분이 좀 어려웠습니다...
아래에 있는 여러 가지 방법으로 시도를 해봤는데 계속 에러가 뜨더라고요.
그래서 Factory를 만들어 해결하였습니다.

2021-06-10 12:58 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +                .get(DiaryListViewModel::class.java)*/
이 부분이 좀 어려웠습니다...
아래에 있는 여러 가지 방법으로 시도를 해봤는데 계속 에러가 뜨더라고요.
그래서 Factory를 만들어 해결하였습니다.

2021-06-10 12:58 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +
이 부분이 좀 어려웠습니다...
아래에 있는 여러 가지 방법으로 시도를 해봤는데 계속 에러가 뜨더라고요.
그래서 Factory를 만들어 해결하였습니다.

2021-06-10 12:59 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +            ViewModelProvider.AndroidViewModelFactory(requireActivity().application).create(DiaryListViewModel::class.java)*/
이 부분이 좀 어려웠습니다...
아래에 있는 여러 가지 방법으로 시도를 해봤는데 계속 에러가 뜨더라고요.
그래서 Factory를 만들어 해결하였습니다.

2021-06-11 00:12 UTC, joyObigo approved these changes
👍👍

2021-06-11 00:12 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +                true
true는 왜 해주어야 하나요? 궁금합니다ㅎㅎ

2021-06-11 00:12 UTC, joyObigo commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +    : RecyclerView.Adapter<DiaryListRecyclerViewAdapter.ViewHolder>() {
DiffUtil과 ListAdpater로 Recyclerview 구현하는 것도 해보면 좋을 것 같아요!
https://thdev.tech/kotlin/2020/09/22/kotlin_effective_03/

2021-06-11 00:12 UTC, joyObigo commented on app/src/main/res/layout/rv_item_diary_list.xml
> +        </LinearLayout>
Linear를 반복해서 쓰지 말고 나중에 customview 를 통해 구현해보는 것도 해보면 좋을 것 같아요~

2021-06-12 12:22 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +                true
true를 주지 않으면 Type mismatch로 에러가 나더라고요!

2021-06-12 12:25 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +    : RecyclerView.Adapter<DiaryListRecyclerViewAdapter.ViewHolder>() {
한번 공부해보아야겠네요!! 
참고자료까지 링크 걸어주셔서 감사합니다~~ :)

2021-06-12 12:26 UTC, Cho2018 commented on app/src/main/res/layout/rv_item_diary_list.xml
> +        </LinearLayout>
오 생각 못한 부분이네요!! 시도해보겠습니다~~

2021-06-13 06:54 UTC, EuneeChung requested changes
DB 작업 머지하면 관련 부분 수정해서 merge하면 좋을 것 같아요
임의로 구현하게 해서 미안합니다 ㅠ 다음엔 좀 더 부지런히 작업해볼게요 ㅎㅎ

저도 부족한게 많아서 서로 코드 리뷰 하면서 더 좋은 방안 생각해봅시다 수고하셨어요 🥰

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val rv : RecyclerView = root.findViewById(R.id.rv_diary_list)
findViewById()보다 데이터 바인딩 공부하셨으니까 데이터 바인딩으로 바꿔보는건 어떨까요??

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/res/layout/rv_item_diary_list.xml
> +                android:textColor="#2B2B2B"/>
디자인 뷰 나오면 리소스에 컬러 코드 저장해서 쓰면 좋을것같아요!

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListViewModel.kt
> +    private val repo = DiaryRepository(application)
레파지토리 구현한 부분에 application을 넘기지 않고 연결할 수 있도록 해놔서 위에 뷰모델 생성도 커스텀을 진행하지 않아도 잘 될것 같아요 !!  제가 더 빨리했어야 했는데 미안합니다 😳

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val btnAdd : Button = root.findViewById(R.id.btn_add)
이 부분도 데이터 바인딩으로 하면 좋을것 같아요 !

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        rv.setHasFixedSize(true)
짧지만 함수로 만들면 어떨까요? 함수 이름으로 어떤 동작을 하는지와 내부 동작은 그 함수만 보면 된다는 장점이 있는것 같아요 !

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +    }
지금 처럼 옵저버를 통해 데이터 갱신하는 방법도 있고 
이부분 internal 함수로 만들고, 바인딩 어댑터를 활용해서 뷰모델이 들고있는 다이어리 리스트와 바로 엮을 수 있는 방법도 있어요 !!
후자의 방법도 적용해보면서 더 좋다고 생각하신  방법으로 쓰시면 될것같아요 ! 

관련 링크 첨부할게요! 
https://hanyeop.tistory.com/213

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/repo/DiaryRepositroy.kt
> +    }
try catch 적용하는거 너무 좋은거 같아요 😉

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/add/AddActivity.kt
> +                finish()
이 부분도 함수로 따로 뺴서 onCreate() 안에 코드의 가독성을 높이면 좋을 것 같아요

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val root = inflater.inflate(R.layout.fragment_diary_list, container, false)
요기도 데이터바인딩 기대하겠습니다 ㅎㅎ

2021-06-13 06:54 UTC, EuneeChung commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.add.AddActivity"></activity>
AddDiary로 이름 짓는건 어떨까요?? 조금 더 명시적일것 같아요!

2021-06-13 08:24 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val rv : RecyclerView = root.findViewById(R.id.rv_diary_list)
기능 구현에 초점을 맞추다 보니 데이터 바인딩 적용이 미흡했네요! 수정하겠습니다!

2021-06-13 08:27 UTC, Cho2018 commented on app/src/main/res/layout/rv_item_diary_list.xml
> +                android:textColor="#2B2B2B"/>
신경쓰지 못한 부분이네요! 감사합니다!! 나중에 디자인 수정 완료되면 수정하겠습니다!!

2021-06-13 08:29 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListViewModel.kt
> +    private val repo = DiaryRepository(application)
아닙니다!! 덕분에 Room 공부 등 열심히 참고해서 하고 있습니다!! 감사합니다~~ 😊

2021-06-13 08:30 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val btnAdd : Button = root.findViewById(R.id.btn_add)
네넵 수정하겠습니다!!

2021-06-13 08:33 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        rv.setHasFixedSize(true)
기능 구현에 초점을 맞춘 거라 함수 등 세세한 작업은 나중에 하려고 했습니다!
다음번에 잊지 않고 작업하여 올리겠습니다~~

2021-06-13 08:37 UTC, Cho2018 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".ui.add.AddActivity"></activity>
임의로 만든 액티비티라 신경쓰지 못했네요!
수정하겠습니다~

2021-06-13 08:39 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/DiaryListFragment.kt
> +        val root = inflater.inflate(R.layout.fragment_diary_list, container, false)
ㅎㅎ 네넵!! 데이터바인딩 잘 적용해보겠습니다 💪

2021-06-13 08:43 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/ui/add/AddActivity.kt
> +                finish()
나중에 사라질 액티비티라 구현이 미흡한 부분이 있네요. 수정하겠습니다~

2021-06-13 08:46 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/adapter/DiaryListRecyclerViewAdapter.kt
> +    }
오 링크까지 감사합니다!!
공부하면서 하고 있어서 부족한 부분이 많은데, 다른 좋은 방안도 알려주셔서 감사합니다! 👍👍
시도해보겠습니다~~

2021-06-30 04:47 UTC, closed without merging