Refactor/18 diaryList
mindgarden-app/mindgarden-android pull request #21
Opened 2021-09-22 05:22 UTC by Cho2018

**merge한 후, hilt 바탕으로 구조 등을 변경했어요
이슈 보시면 아시겠지만 몇 가지 알릴 사항이 있습니다**

1. Diary : 기본키인 인덱스가 자동으로 알아서 카운팅 되도록 수정했습니다.
2. DiaryList : 우선 date 상관없이 list 조회하도록 했습니다. (getAll() , loadAll() 이용) - 추후 달마다 조회해서 가져오는 거 구현할게요!
3. Room : Room 관련 오류가 떠서 찾아보니 버전을 올리고 마이그레이션 관련 작업을 진행하면 되더라고요. 그래서 수정했습니다. 
아래는 참고 링크입니다.
https://raphaelh.tistory.com/41
https://android-dev.tistory.com/49

2021-09-22 05:29 UTC, Cho2018 commented on app/src/main/AndroidManifest.xml
> +        android:allowBackup="false"
Room 관련 오류 때문에 수정했어요
참고 링크는 위에 적어 두었습니다!

2021-09-22 05:29 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/model/entity/Diary.kt
> +    @PrimaryKey(autoGenerate = true)
기본키 인덱스는 autoGenerate가 편할 것 같아 이렇게 수정했어요

2021-09-22 05:29 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/database/MindgardenDatabase.kt
> +@Database(entities = [Garden::class, Diary::class, User::class], version = 2, exportSchema = false)
오류로 버전을 2로 수정했습니다

2021-09-22 05:29 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/database/MindgardenDatabase.kt
> +            ).fallbackToDestructiveMigration().build()
이 부분 역시 오류 때문에 추가하였습니다

2021-09-22 05:29 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/diaryRepo/DefaultDiaryRepository.kt
> +    override fun getAll(): Flowable<List<Diary>> {
우선 date 상관없이 전체 list 조회하도록 했습니다!
나중에 수정하겠습니다!

2021-09-22 05:59 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/database/MindgardenDatabase.kt
> +@Database(entities = [Garden::class, Diary::class, User::class], version = 2, exportSchema = false)
entity에 변화가 생겼고 기기(avd, 모바일)에 이미 변경 전 db를 가진 앱이 설치되어 있어서 충돌이 난 것 같은데,
제 생각에는 release가 아니고 build 단계니까 마이그레이션 하는 작업 없이
기기에 있는 앱을 삭제하고 다시 빌드 했어도 됐을 것 같아요!

2021-09-22 06:36 UTC, godjoy commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/diaryRepo/DefaultDiaryRepository.kt
> +    override fun getAll(): Flowable<List<Diary>> {
공부하고 있으면 나중에 Flowable에 대해서 정리해주세요ㅎㅎ

2021-09-22 06:51 UTC, godjoy requested changes
잘봤습니다
Diary list 조회까지 성공했다니~
 hilt 적용하고 repo 구조 바꾼다고 중간 중간 많이 바뀌어서 변경 사항 넣느라 힘들었을 수도 있는데 ㅎㅎ 
Room 관련 에러 사항은 제가 리뷰로 달아둔 부분 보고 한번 해본 다음에 고치는 건 어떨까요?
결과 공유 부탁드려요!

2021-09-25 10:48 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/database/MindgardenDatabase.kt
> +@Database(entities = [Garden::class, Diary::class, User::class], version = 2, exportSchema = false)
오 그러네요!!
Room 관련 수정 사항들 다시 원상 복구했습니다!
감사합니다~~

2021-09-25 10:49 UTC, Cho2018 commented on app/src/main/java/com/mindgarden/mindgarden/data/repository/diaryRepo/DefaultDiaryRepository.kt
> +    override fun getAll(): Flowable<List<Diary>> {
네넵~~!! 😊

2021-09-25 10:57 UTC, godjoy approved these changes

2021-09-25 10:58 UTC, EuneeChung commented
우와 완전 열심히 한게 느껴져요 !! hilt 랑 룸 적용하느라 고생하셨습니다!!
오류 고친 부분 보고 저도 작업할때 참고 하겠습니다 ㅎㅎ

2021-09-25 11:02 UTC, EuneeChung approved these changes

2021-09-25 11:02 UTC, EuneeChung commented on app/src/main/java/com/mindgarden/mindgarden/ui/diarylist/SwipeHelperCallBack.kt
> +class SwipeHelperCallBack : ItemTouchHelper.Callback() {
이 친구 궁금했는데 이걸로 하셨군요! 나중에 저도 참고하겠습니다 ~

2021-09-25 11:06 UTC, merged